version: '3.1'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 8883:8883
    volumes:
      - ./config:/mosquitto/config
